apiVersion: v1
kind: Namespace
metadata:
  name: dummy
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  labels:
    kubernetes.io/metadata.name: dummy
    argocd.argoproj.io/managed-by: argocd-applications
