apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: components/rbac/overlays/default
    repoURL: ssh://git@gitserver.tools.svc:2022/home/git/repos/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
