apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-applications
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '90'
spec:
  # must whitelist creation of namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'console.openshift.io'
    kind: ConsoleLink
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: argocd-applications
    server: https://kubernetes.default.svc
  sourceRepos:
  - ssh://git@gitserver.tools.svc:2022/home/git/repos/cluster-config.git

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '90'
spec:
  destination:
    namespace: argocd-applications
    server: https://kubernetes.default.svc
  project: argocd-applications
  source:
    path: components/argocd-applications/overlays/default
    repoURL: ssh://git@gitserver.tools.svc:2022/home/git/repos/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      #prune: false
      #selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
