apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- 10-storage.yaml
- 20-rbac.yaml
- 30-operators.yaml
- 40-tools.yaml
- 90-argocd-applications.yaml

patches:
- target:
    kind: Application
    group: argoproj.io
    name: cluster-config
  patch: |-
    - op: replace
      path: /spec/source/path
      value: clusters/overlays/default

# patches:
# - target:
#     kind: argoproj.io
#     group: v1alpha1
#     name: default
#     namespace: openshift-gitops
#   patch: |-
#     - op: replace
#       path: /spec/clusterResourceWhitelist
#       value: []
#     - op: replace
#       path: /spec/namespaceResourceWhitelist
#       value: []
#     - op: replace
#       path: /spec/clusterResourceBlacklist
#       value:
#         - group: '*'
#           kind: '*'
#     - op: replace
#       path: /spec/namespaceResourceBlacklist
#       value:
#         - group: '*'
#           kind: '*'
#     - op: replace
#       path: /spec/sourceRepos
#       value: []
