apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitserver
  name: gitserver
spec:
  type: ClusterIP
  ports:
  - name: 2022-2022
    port: 2022
    protocol: TCP
    targetPort: 2022
  selector:
    deployment: gitserver
