apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops
  namespace: openshift-operators
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops
  source: redhat-operator-index
  sourceNamespace: openshift-marketplace
  #startingCSV: openshift-gitops-operator.v1.6.1
  config:
    env:
    - name: DISABLE_DEX
      value: ''
