apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps
  namespace: argocd-applications
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  namespaceResourceWhitelist:
  - group: app.k8s.io
    kind: Application
  - group: app.k8s.io
    kind: AppProject
  - group: argoproj.io
    kind: Application
  - group: argoproj.io
    kind: AppProject
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  destinations:
  - namespace: argocd-applications
    server: https://kubernetes.default.svc
  sourceRepos:
  - ssh://git@gitserver.tools.svc:2022/home/git/repos/cluster-config.git

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd-applications
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  destination:
    namespace: argocd-applications
    server: https://kubernetes.default.svc
  project: app-of-apps
  source:
    path: components/argocd-applications/applications/overlays/default
    repoURL: ssh://git@gitserver.tools.svc:2022/home/git/repos/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      #prune: true
      #selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground

---
