apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-argocd-applications-namespace.yaml
- 10-argocd-applications-argocd.yaml
- 20-consolelink.yaml
- 30-app-of-apps-application.yaml
