apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- path: oauth-cluster-patch.yaml
  target:
    group: config.openshift.io
    version: v1
    kind: OAuth
    name: cluster
