apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - ssh://git@gitserver.tools.svc:2022/home/git/repos/cluster-config.git

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: openshift-gitops
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io # cascade delete resources with Application
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: clusters/overlays/default # manage self
    repoURL: ssh://git@gitserver.tools.svc:2022/home/git/repos/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      #prune: true
      #selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
