apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster
  source:
    path: components/argocd-applications/overlays/default
    repoURL: ssh://git@gitserver.tools.svc:2022/home/git/repos/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      prune: false
      selfHeal: false
    syncOptions:
    - PrunePropagationPolicy=foreground
