apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- application-oauth.yaml
- application-argocd-applications.yaml

patches:
- path: argocd-openshift-gitops-patch.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: ArgoCD
    name: openshift-gitops
