apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: htpasswd-users
    namespace: openshift-config
stringData:
    htpasswd: ENC[AES256_GCM,data:vz1vdA0uQiOpR1f+JAT/HlUT1wKRDkZhGfQW+ZY78i51WheGBiWpnWO1Ibc3E4SAjiTItkHNcxrV+zftxEtsY7ekWd64EtV+Hr87nxc3mMn+u/kayK7e6ui4BlYgGSb/5Zo37qD0OevIoS3D75UyNPZCCnzbsbVvCDKJDI9DWChhI6k0BYE=,iv:h0Gr7sWos/p5lVCKr4zHO3Zc3AhDi0YnUvbkdvsRfj8=,tag:/YtIH4+5gmEWvOdRDb5VwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1helqcqsh9464r8chnwc2fzj8uv7vr5ntnsft0tn45v2xtz0hpfwq98cmsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYkhXVEtFejlULy9YZTE0
            VzliOWlRMUNTMzg2VXIzOUFjdzdKbUIyMncwCmplVXdKK0hUZjVtNnE0dkxoYzl6
            RFU4UHhLSWVnaXR4SG5TV210VlZvNDAKLS0tIEZiOVMyMTJObXoyK2YrNlU2bEtH
            MEJYVDRPbzBzSVRYcXlqSGVOOTFZME0KJQK1vlNY1x1uA7dQ5m2ZjS5GzHb+s1hG
            Hh1hKv6FIHurVq6U2oDpKBWrTbFZ8yM5vFZvk3HyrK4tIIvXCBeoGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-18T18:23:00Z"
    mac: ENC[AES256_GCM,data:VGvDbWXqSk77IhI2UO6M5xJ/jJWPIdjSgnuKpq7U1VEz2Zlz50yx9zV5CCHehA+CP6aZmdC5KkG+MNCwP7CBgSlnHkpF9UxghNvMWtDdeIxv7Wa0ikxpOYGpOgnO3nRuep3kNOu66NjQyusKNcCOxIBMQK7KBqOP+xBLlROpAY4=,iv:pgZlgmqRCSnS4jh4a5wgMaTn2OnZ30F6+ANb/lmAhQU=,tag:eGkg2WgvQTvSh/htb4nmIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
