apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dummy
  namespace: argocd-applications
spec:
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - ssh://git@gitserver.tools.svc:2022/home/git/repos/cluster-config.git

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy
  namespace: argocd-applications
spec:
  destination:
    namespace: dummy
    server: https://kubernetes.default.svc
  project: argocd-applications
  source:
    path: dummy-application/overlays/default
    repoURL: ssh://git@gitserver.tools.svc:2022/home/git/repos/cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      #prune: true
      #selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
