- op: replace
  path: /spec/resourceCustomizations
  # Add health assessment for Applications to use them with sync waves for app-of-apps
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.7-1.8/#health-assessment-of-argoprojioapplication-crd-has-been-removed
  # https://github.com/argoproj/argo-cd/issues/3781
  value: |
    health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
- op: replace
  path: /spec/rbac
  value:
    defaultPolicy: role:readonly
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, application-admins, role:admin
