apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- application-dummy.yaml
- configmap-argocd-ssh-known-hosts-cm.yaml

patches:
- path: argocd-argocd-applications-patch.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: ArgoCD
    name: argocd-applications
